apiVersion: apps/v1
kind: Deployment
metadata:
  name: isyweather
  annotations:
    dev: mprattinger
spec:
  replicas: 1
  selector:
    matchLabels:
      app: isyweather
  template:
    metadata:
      labels:
        app: isyweather
    spec:
      volumes:
      - name: isyweather-config-volume
        configMap:
          name: isyweather-config
      containers:
      - image: becom.azurecr.io/isyweather:latest
        imagePullPolicy: Always
        name: isyweather
        volumeMounts:
          - name: isyweather-config-volume 
            mountPath: /app/weatherconfig
        ports:
        - containerPort: 80
      imagePullSecrets:
        - name: acr